#!/usr/bin/python

CONST_QUIET = False
CONST_MAX_ROUTE_REPAIR_DIST = 3
CONST_SEARCH_DEPTH_BIAS = 8
CONST_MAX_GROPE_DIST = 10
CONST_SEARCH_HOTSPOT_BIAS = 99
CONST_SEARCH_MULTIWALL_BIAS = 9
CONST_KICK_DOOR_COST = 5